site_name: MoveOrDevelop
repo_url: https://github.com/RamiLego4Game/MoDev/
pages:
- Home: index.md
- File Index:
  - 'Engine':
    - 'GlobalVariables.el': 'Engine/GlobalVariables.md'
theme: readthedocs
