site_name: MoveOrDevelop
repo_url: https://github.com/RamiLego4Game/MoDev/
pages:
- Home: index.md
- Code Files Index:
  - Engine:
    - 'GlobalVariables.el': 'Engine/GlobalVariables.md'
    - 'effectBase.el': 'Engine/effectBase.md'
  - Src:
    - 'MinigameUtility.el': 'Src/MinigameUtility.md'
theme: readthedocs
